version: "3"
networks:
  netw1:
volumes:
  asd:
services:
  web1:
    image: nyo
    container_name : tr
    ports:
      - "8083:80"
    volumes:
      - /host/asd:/container/data
    networks:
      - netw1
